services:
  - type: web
    name: brain-tumor-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mysite.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
