# Generated by Django 4.2 on 2026-03-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='gradcam_b64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
